//定义常量接口

export const  RECEIVE_POLICYDESCLIST   = "receive_policydesclist"
export const  RECEIVE_CATELIST   = "receive_catelist"
export const  RECEIVE_FOCUSLIST   = "receive_focuslist"
export const  RECEIVE_KINGKONGLIST   = "receive_kingkonglist"
export const  RECEIVE_INDEXACTIVITYMODULE   = "receive_indexactivitymodule"
export const  RECEIVE_CATEGORYLIST   = "receive_categorylist"
export const  RECEIVE_CATEGORY   = "receive_category"
// export const  RECEIVE_RECOMMEND   = "receive_recommend"
export const  RECEIVE_FINDTAB   = "receive_findtab"
export const  RECEIVE_FINDDATA   = "receive_finddata"
export const  RECEIVE_FINDDATA2   = "receive_finddata2"
export const  RECEIVE_USER   = "receive_user"
export const  RESET_USER   = "reset_user"
export const  RECEIVE_SEARCHTAB   = "receive_searchtab"
export const  RECEIVE_SEARCHKEY   = "receive_searchkey"
